/**
 * useFileUpload Hook
 *
 * Reusable hook for file upload functionality:
 * - Drag and drop upload
 * - Paste from clipboard
 * - Auto-convert long text to markdown file
 * - File preview
 */

import { useState, useCallback, useEffect, useRef } from 'react';

export interface FileUploadOptions {
  /** Max text length before auto-convert to file */
  maxTextLength?: number;
  /** Auto-convert long text to markdown file */
  autoConvertLongText?: boolean;
  /** File name prefix for auto-generated files */
  autoFileNamePrefix?: string;
  /** Max file size in bytes (default: 50MB) */
  maxFileSize?: number;
  /** Allowed file extensions (empty = all allowed) */
  allowedExtensions?: string[];
  /** Callback when files change */
  onFilesChange?: (files: File[]) => void;
}

export interface FileUploadResult {
  /** Current file list */
  fileList: File[];
  /** Set file list */
  setFileList: React.Dispatch<React.SetStateAction<File[]>>;
  /** Add files to list */
  addFiles: (files: File[]) => void;
  /** Remove file by index */
  removeFile: (index: number) => void;
  /** Clear all files */
  clearFiles: () => void;
  /** Index of auto-generated file (-1 if none) */
  autoGeneratedFileIndex: number | null;
  /** Drag state */
  isDragging: boolean;
  /** Drag event handlers */
  dragHandlers: {
    onDragOver: (e: React.DragEvent) => void;
    onDragLeave: (e: React.DragEvent) => void;
    onDrop: (e: React.DragEvent) => void;
  };
  /** Paste handler */
  handlePaste: (e: React.ClipboardEvent) => void;
  /** Check if text would trigger auto-convert */
  shouldAutoConvert: (text: string) => boolean;
  /** Manually trigger auto-convert */
  convertTextToFile: (text: string, filename?: string) => File | null;
}

export function useFileUpload(options: FileUploadOptions = {}): FileUploadResult {
  const {
    maxTextLength = 1000,
    autoConvertLongText = true,
    autoFileNamePrefix = 'input',
    maxFileSize = 50 * 1024 * 1024, // 50MB
    allowedExtensions = [],
    onFilesChange,
  } = options;

  const [fileList, setFileList] = useState<File[]>([]);
  const [autoGeneratedFileIndex, setAutoGeneratedFileIndex] = useState<number | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const isAutoConverting = useRef(false);

  // Notify on files change
  useEffect(() => {
    onFilesChange?.(fileList);
  }, [fileList, onFilesChange]);

  // Validate file
  const validateFile = useCallback((file: File): boolean => {
    // Check file size
    if (file.size > maxFileSize) {
      console.warn(`File ${file.name} exceeds max size limit`);
      return false;
    }

    // Check extension if specified
    if (allowedExtensions.length > 0) {
      const ext = file.name.split('.').pop()?.toLowerCase();
      if (!ext || !allowedExtensions.includes(`.${ext}`) && !allowedExtensions.includes(ext)) {
        console.warn(`File extension .${ext} is not allowed`);
        return false;
      }
    }

    return true;
  }, [maxFileSize, allowedExtensions]);

  // Add files
  const addFiles = useCallback((files: File[]) => {
    const validFiles = files.filter(validateFile);
    if (validFiles.length > 0) {
      setFileList(prev => [...prev, ...validFiles]);
    }
  }, [validateFile]);

  // Remove file
  const removeFile = useCallback((index: number) => {
    setFileList(prev => {
      const newList = [...prev];
      newList.splice(index, 1);
      return newList;
    });
    // Clear auto-generated index if removing that file
    if (index === autoGeneratedFileIndex) {
      setAutoGeneratedFileIndex(null);
    }
  }, [autoGeneratedFileIndex]);

  // Clear all files
  const clearFiles = useCallback(() => {
    setFileList([]);
    setAutoGeneratedFileIndex(null);
  }, []);

  // Check if text should auto-convert
  const shouldAutoConvert = useCallback((text: string): boolean => {
    return autoConvertLongText && text.length > maxTextLength;
  }, [autoConvertLongText, maxTextLength]);

  // Convert text to markdown file
  const convertTextToFile = useCallback((text: string, filename?: string): File | null => {
    if (!text.trim()) return null;

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const name = filename || `${autoFileNamePrefix}-${timestamp}.md`;

    const header = `# 对话输入内容

生成时间: ${new Date().toLocaleString()}
字符数: ${text.length}

---

`;
    const content = header + text;
    const blob = new Blob([content], { type: 'text/markdown' });
    return new File([blob], name, { type: 'text/markdown' });
  }, [autoFileNamePrefix]);

  // Auto-convert effect
  const checkAndAutoConvert = useCallback((text: string, setText: (text: string) => void) => {
    if (!autoConvertLongText || isAutoConverting.current) return;
    if (text.length <= maxTextLength) return;
    if (autoGeneratedFileIndex !== null) return;

    isAutoConverting.current = true;

    const file = convertTextToFile(text);
    if (file) {
      const currentIndex = fileList.length;
      setFileList(prev => [...prev, file]);
      setAutoGeneratedFileIndex(currentIndex);
      setText(''); // Clear input after converting
    }

    setTimeout(() => {
      isAutoConverting.current = false;
    }, 100);
  }, [autoConvertLongText, maxTextLength, autoGeneratedFileIndex, fileList.length, convertTextToFile]);

  // Drag handlers
  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const files = Array.from(e.dataTransfer.files);
    addFiles(files);
  }, [addFiles]);

  // Paste handler
  const handlePaste = useCallback((e: React.ClipboardEvent) => {
    const items = e.clipboardData?.items;
    if (!items) return;

    const files: File[] = [];

    for (let i = 0; i < items.length; i++) {
      const item = items[i];
      if (item.kind === 'file') {
        const file = item.getAsFile();
        if (file) {
          files.push(file);
        }
      }
    }

    if (files.length > 0) {
      e.preventDefault();
      addFiles(files);
    }
  }, [addFiles]);

  const dragHandlers = {
    onDragOver: handleDragOver,
    onDragLeave: handleDragLeave,
    onDrop: handleDrop,
  };

  return {
    fileList,
    setFileList,
    addFiles,
    removeFile,
    clearFiles,
    autoGeneratedFileIndex,
    isDragging,
    dragHandlers,
    handlePaste,
    shouldAutoConvert,
    convertTextToFile,
  };
}

export default useFileUpload;