"""Auto reasoning_engine chat manager agent."""

import logging

from derisk.agent import ProfileConfig
from derisk.agent.core.plan.react.team_react_plan import ReActPlanChatManager

from derisk.util.configure import DynConfig

logger = logging.getLogger(__name__)


class SreManager(ReActPlanChatManager):
    """A chat manager agent that can manage a team chat of multiple agents."""

    profile: ProfileConfig = ProfileConfig(
        name=DynConfig(
            "AI-SRE(DeRisk)",
            category="agent",
            key="derisk_agent_team_sre_profile_name",
        ),
        role=DynConfig(
            "AI-SRE(DeRisk)",
            category="agent",
            key="derisk_agent_team_sre_profile_role",
        ),
        goal=DynConfig(
            "Advance the task reasoning_engine generated by the planning agent. If the reasoning_engine "
            "does not pre-allocate an agent, it needs to be coordinated with the "
            "appropriate agent to complete.",
            category="agent",
            key="derisk_agent_team_sre_profile_goal",
        ),
        desc=DynConfig(
            "Advance the task reasoning_engine generated by the planning agent.",
            category="agent",
            key="derisk_agent_team_sre_profile_desc",
        ),
        avatar="derisk.jpg",
    )
    concurrency_limit: int = 6
    # 当前Agent消息是否显示
    show_message: bool = True
    current_goal: str = None

    def __init__(self, **kwargs):
        """Create a new AutoPlanChatManager instance."""
        super().__init__(**kwargs)
