/**
 * FilePreview Component
 *
 * Reusable file preview component with:
 * - Image preview
 * - Markdown file special styling
 * - Auto-generated file indicator
 * - Remove button
 */

'use client';

import { useEffect, useState } from 'react';
import { FileTextOutlined } from '@ant-design/icons';

interface FilePreviewProps {
  file: File;
  onRemove: () => void;
  isAutoGenerated?: boolean;
  showFileName?: boolean;
  size?: 'small' | 'medium' | 'large';
}

export function FilePreview({
  file,
  onRemove,
  isAutoGenerated = false,
  showFileName = true,
  size = 'medium',
}: FilePreviewProps) {
  const [preview, setPreview] = useState<string>('');

  useEffect(() => {
    if (file.type.startsWith('image/')) {
      const url = URL.createObjectURL(file);
      setPreview(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [file]);

  const isMarkdown = file.name.endsWith('.md') || file.type === 'text/markdown';

  const sizeClasses = {
    small: 'w-8 h-8',
    medium: 'w-10 h-10',
    large: 'w-12 h-12',
  };

  // Markdown file with auto-generated styling
  if (isMarkdown) {
    return (
      <div className="flex items-center gap-2 px-3 py-2 rounded-lg border border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-900/20 hover:bg-blue-50 dark:hover:bg-blue-900/30 transition-colors group">
        <div className="w-8 h-10 rounded bg-white dark:bg-gray-800 shadow-sm border border-gray-200 dark:border-gray-700 flex flex-col items-center justify-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-3 h-3 bg-blue-500" style={{ clipPath: 'polygon(100% 0, 0 0, 100% 100%)' }}></div>
          <FileTextOutlined className="text-blue-500 text-lg" />
          <span className="text-[8px] text-blue-600 dark:text-blue-400 font-medium mt-0.5">MD</span>
        </div>
        <div className="flex flex-col min-w-0">
          <span className="text-xs font-medium text-gray-700 dark:text-gray-300 truncate max-w-[120px]">
            {isAutoGenerated ? '输入内容' : file.name}
          </span>
          <span className="text-[10px] text-gray-400">
            {(file.size / 1024).toFixed(1)} KB · Markdown
          </span>
        </div>
        <button
          className="ml-1 p-1 rounded-full hover:bg-red-100 dark:hover:bg-red-900/30 text-gray-400 hover:text-red-500 transition-colors"
          onClick={(e) => {
            e.stopPropagation();
            onRemove();
          }}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
    );
  }

  // Image preview
  if (file.type.startsWith('image/')) {
    return (
      <div className={`relative group flex-shrink-0 ${sizeClasses[size]} rounded-lg border border-gray-100 dark:border-gray-700 overflow-hidden bg-white dark:bg-[#1F1F1F]`}>
        <img src={preview} alt={file.name} className="w-full h-full object-cover" />
        <div
          className="absolute -top-1 -right-1 w-5 h-5 bg-black/50 hover:bg-red-500 rounded-full flex items-center justify-center cursor-pointer transition-all opacity-0 group-hover:opacity-100 backdrop-blur-sm"
          onClick={(e) => {
            e.stopPropagation();
            onRemove();
          }}
        >
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </div>
      </div>
    );
  }

  // Default file preview
  return (
    <div className={`relative group flex-shrink-0 ${sizeClasses[size]} rounded-lg border border-gray-100 dark:border-gray-700 overflow-hidden bg-white dark:bg-[#1F1F1F]`}>
      <div className="w-full h-full flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-800 gap-0.5">
        <FileTextOutlined className="text-gray-400 text-lg" />
        {showFileName && (
          <span className="text-[9px] text-gray-400 truncate w-full text-center px-1">
            {file.name}
          </span>
        )}
      </div>
      <div
        className="absolute -top-1 -right-1 w-5 h-5 bg-black/50 hover:bg-red-500 rounded-full flex items-center justify-center cursor-pointer transition-all opacity-0 group-hover:opacity-100 backdrop-blur-sm"
        onClick={(e) => {
          e.stopPropagation();
          onRemove();
        }}
      >
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
          <path d="M18 6L6 18M6 6l12 12" />
        </svg>
      </div>
    </div>
  );
}

/**
 * FilePreviewList Component
 *
 * Displays a list of file previews with horizontal scrolling
 */

interface FilePreviewListProps {
  files: File[];
  onRemove: (index: number) => void;
  autoGeneratedIndex?: number | null;
  size?: 'small' | 'medium' | 'large';
}

export function FilePreviewList({
  files,
  onRemove,
  autoGeneratedIndex = null,
  size = 'medium',
}: FilePreviewListProps) {
  if (files.length === 0) return null;

  return (
    <div className="flex gap-2 overflow-x-auto scrollbar-hide pb-2">
      {files.map((file, index) => (
        <FilePreview
          key={`${index}-${file.name}`}
          file={file}
          onRemove={() => onRemove(index)}
          isAutoGenerated={index === autoGeneratedIndex}
          size={size}
        />
      ))}
    </div>
  );
}

export default FilePreview;