"""
Agent Core V2 - 重构后的Agent核心模块

本模块包含完整的Agent平台核心组件:
- AgentInfo: Agent配置模型
- Permission: 权限系统
- AgentBase: Agent基类
- Goal: 目标管理系统
- Interaction: 交互协议系统
- ModelProvider: 模型供应商抽象层
- ModelMonitor: 模型调用监控追踪
- MemoryCompaction: 记忆压缩机制
- MemoryVector: 向量检索系统
- SandboxDocker: Docker沙箱执行
- ReasoningStrategy: 推理策略系统
- Observability: 可观测性系统
- ConfigManager: 配置管理系统
- TaskScene: 任务场景与策略配置
- SceneRegistry: 场景注册中心
- ModeManager: 模式切换管理器
- ContextProcessor: 上下文处理器

Enhanced (v3): User Interaction and Recovery System
- EnhancedInteractionManager: Enhanced interaction with WebSocket support
- RecoveryCoordinator: Interrupt recovery and Todo management
- Full interaction protocol support
- Checkpoint and resume capabilities
"""

from .agent_info import (
    AgentInfo,
    AgentMode,
    PermissionAction,
    PermissionRule,
    PermissionRuleset,
)
from .permission import (
    PermissionChecker,
    PermissionRequest,
    PermissionResponse,
    PermissionDeniedError,
    PermissionManager,
    InteractivePermissionChecker,
    permission_manager,
)
from .agent_base import (
    AgentBase,
    AgentContext,
    AgentState,
    AgentMessage,
    AgentExecutionResult,
    SimpleAgent,
)

from .goal import (
    Goal,
    GoalStatus,
    GoalPriority,
    SuccessCriterion,
    CriterionType,
    GoalManager,
    Task,
    TaskTracker,
    GoalDecompositionStrategy,
    goal_manager,
)

from .interaction import (
    InteractionType,
    InteractionPriority,
    InteractionStatus,
    InteractionRequest,
    InteractionResponse,
    InteractionOption,
    InteractionHandler,
    InteractionManager,
    BatchInteractionManager,
    CLIInteractionHandler,
    WebSocketInteractionHandler,
    NotifyLevel,
    interaction_manager,
)

from .model_provider import (
    ModelProvider,
    ModelConfig,
    ModelMessage,
    ModelResponse,
    ModelUsage,
    StreamChunk,
    CallOptions,
    ModelCapability,
    ModelRegistry,
    ModelClient,
    OpenAIProvider,
    AnthropicProvider,
    model_registry,
)

from .model_monitor import (
    ModelMonitor,
    CallStatus,
    SpanKind,
    ModelCallSpan,
    TokenUsage,
    TokenUsageTracker,
    CallTrace,
    CostBudget,
    model_monitor,
)

from .memory_compaction import (
    MemoryMessage,
    CompactionStrategy,
    KeyInfo,
    CompactionResult,
    ImportanceScorer,
    KeyInfoExtractor,
    SummaryGenerator,
    MemoryCompactor,
    MemoryCompactionManager,
)

from .memory_vector import (
    VectorDocument,
    SearchResult,
    EmbeddingModel,
    OpenAIEmbedding,
    SimpleEmbedding,
    VectorStore,
    InMemoryVectorStore,
    VectorMemoryStore,
    MemoryRetriever,
    vector_memory_store,
)

from .sandbox_docker import (
    SandboxType,
    SandboxStatus,
    SandboxConfig,
    SandboxBase,
    LocalSandbox,
    DockerSandbox,
    SandboxManager,
    ExecutionResult,
    sandbox_manager,
)

from .reasoning_strategy import (
    ReasoningStrategy,
    ReasoningStep,
    ReasoningResult,
    StrategyType,
    ReActStrategy,
    PlanAndExecuteStrategy,
    ChainOfThoughtStrategy,
    ReflectionStrategy,
    ReasoningStrategyFactory,
    reasoning_strategy_factory,
)

from .observability import (
    MetricType,
    LogLevel,
    SpanStatus,
    Metric,
    Span,
    LogEntry,
    MetricsCollector,
    Tracer,
    StructuredLogger,
    ObservabilityManager,
    observability_manager,
)

from .config_manager import (
    ConfigSource,
    ConfigChange,
    ConfigVersion,
    AgentConfig,
    ConfigSchema,
    ConfigLoader,
    ConfigValidator,
    ConfigManager,
    GlobalConfig,
    get_config,
    set_config,
    config_manager,
)

from .agent_harness import (
    ExecutionState,
    CheckpointType,
    ContextLayer,
    ExecutionContext,
    Checkpoint,
    ExecutionSnapshot,
    StateStore,
    FileStateStore,
    MemoryStateStore,
    CheckpointManager,
    CircuitBreaker,
    TaskQueue,
    StateCompressor,
    AgentHarness,
    agent_harness,
)

from .context_validation import (
    ValidationLevel,
    ValidationCategory,
    ValidationResult,
    ContextValidator,
    LayeredContextValidator,
    ContextValidationManager,
    context_validator,
    layered_context_validator,
    context_validation_manager,
)

from .execution_replay import (
    ReplayEventType,
    ReplayMode,
    ReplayEvent,
    ExecutionRecording,
    ExecutionReplayer,
    ExecutionAnalyzer,
    ReplayManager,
    replay_manager,
)

from .long_task_executor import (
    LongTaskStatus,
    ProgressPhase,
    ProgressReport,
    LongTaskConfig,
    LongRunningTaskExecutor,
    long_running_task_executor,
)

from .tools_v2 import (
    ToolMetadata,
    ToolResult,
    ToolBase,
    ToolRegistry,
    tool,
    register_builtin_tools,
    BashTool,
    ReadTool,
    WriteTool,
    ListFilesTool,
    AskUserTool,
    QuestionTool,  # 向后兼容别名
    register_interaction_tools,
    WebFetchTool,
    WebSearchTool,
    APICallTool,
    GraphQLTool,
    register_network_tools,
    MCPToolAdapter,
    MCPToolRegistry,
    MCPConnectionManager,
    adapt_mcp_tool,
    register_mcp_tools,
    mcp_connection_manager,
    ActionToolAdapter,
    ActionToolRegistry,
    action_to_tool,
    register_actions_from_module,
    create_action_tools_from_resources,
    ActionTypeMapper,
    default_action_mapper,
    register_analysis_tools,
    register_all_tools,
    create_default_tool_registry,
)

from .visualization import (
    ProgressEventType,
    ProgressEvent,
    ProgressBroadcaster,
    progress_broadcaster,
)

from .llm_adapter import (
    LLMProvider,
    MessageRole,
    LLMMessage,
    LLMUsage,
    LLMResponse,
    LLMConfig,
    LLMAdapter,
    OpenAIAdapter,
    AnthropicAdapter,
    LLMFactory,
    llm_factory,
)

from .production_agent import (
    ProductionAgent,
    AgentBuilder,
)
from .production_interaction import (
    ProductionAgentInteractionMixin,
    ProductionAgentWithInteraction,
)

from .task_scene import (
    TaskScene,
    TruncationStrategy,
    DedupStrategy,
    ValidationLevel,
    OutputFormat,
    ResponseStyle,
    TruncationPolicy,
    CompactionPolicy,
    DedupPolicy,
    TokenBudget,
    ContextPolicy,
    PromptPolicy,
    ToolPolicy,
    SceneProfile,
    SceneProfileBuilder,
    create_scene,
)

from .context_processor import (
    ProcessResult,
    ProtectedBlock,
    ContextProcessor,
    ContextProcessorFactory,
)

from .scene_registry import (
    SceneRegistry,
    get_scene_profile,
    list_available_scenes,
    create_custom_scene,
)

from .mode_manager import (
    ModeSwitchResult,
    ModeHistory,
    ModeManager,
    ModeManagerFactory,
    get_mode_manager,
)

from .scene_config_loader import (
    SceneConfigError,
    SceneConfigLoader,
    scene_config_loader,
    load_scene_config,
    load_scenes_from_directory,
)

from .scene_strategy import (
    AgentPhase,
    HookPriority,
    HookResult,
    HookContext,
    SceneHook,
    PromptTemplate,
    SystemPromptTemplate,
    ContextProcessorExtension,
    ToolSelectorExtension,
    OutputRendererExtension,
    SceneStrategy,
    SceneStrategyRegistry,
    SceneStrategyExecutor,
    scene_hook,
    create_simple_hook,
)

from .scene_strategies_builtin import (
    GENERAL_SYSTEM_PROMPT,
    CODING_SYSTEM_PROMPT,
    GENERAL_STRATEGY,
    CODING_STRATEGY,
    CodeBlockProtectionHook,
    FilePathPreservationHook,
    CodeStyleInjectionHook,
    ProjectContextInjectionHook,
    ToolOutputFormatterHook,
    ErrorRecoveryHook,
    register_builtin_strategies,
)

from .software_engineering_loader import (
    SoftwareEngineeringConfigLoader,
    SoftwareEngineeringConfig,
    CodeQualityChecker,
    DesignPrinciple,
    AntiPattern,
    QualityGate,
    SecurityConstraint,
    get_software_engineering_config,
    check_code_quality,
)

from .software_engineering_integrator import (
    SoftwareEngineeringIntegrator,
    CodingStrategyEnhancer,
    EngineeringCheckResult,
    CheckPoint,
    create_coding_strategy_enhancer,
    integrate_with_agent,
)

from .se_loader_v2 import (
    SoftwareEngineeringLoaderV2,
    LightweightCodeChecker,
    LightConfig,
    FullConfig,
    InjectionLevel,
    DevScene,
    get_se_loader,
    get_light_se_prompt,
    get_standard_se_prompt,
    quick_code_check,
)

from .se_hooks import (
    SoftwareEngineeringHook,
    SoftwareEngineeringCheckHook,
    create_se_hooks,
)

# VIS Push Manager
from .vis_push_manager import (
    VISPushManager,
    VISPushConfig,
    create_vis_push_manager,
)

# VIS Push Hooks
from .vis_push_hooks import (
    VISPushHook,
    VISPushThinkHook,
    VISPushToolHook,
    create_vis_push_hooks,
)

__all__ = [
    "AgentInfo",
    "AgentMode",
    "PermissionAction",
    "PermissionRule",
    "PermissionRuleset",
    "PermissionChecker",
    "PermissionRequest",
    "PermissionResponse",
    "PermissionDeniedError",
    "PermissionManager",
    "InteractivePermissionChecker",
    "permission_manager",
    "AgentBase",
    "AgentContext",
    "AgentState",
    "AgentMessage",
    "AgentExecutionResult",
    "SimpleAgent",
    "Goal",
    "GoalStatus",
    "GoalPriority",
    "SuccessCriterion",
    "CriterionType",
    "GoalManager",
    "Task",
    "TaskTracker",
    "GoalDecompositionStrategy",
    "goal_manager",
    "InteractionType",
    "InteractionPriority",
    "InteractionStatus",
    "InteractionRequest",
    "InteractionResponse",
    "InteractionOption",
    "InteractionHandler",
    "InteractionManager",
    "BatchInteractionManager",
    "CLIInteractionHandler",
    "WebSocketInteractionHandler",
    "NotifyLevel",
    "interaction_manager",
    "ModelProvider",
    "ModelConfig",
    "ModelMessage",
    "ModelResponse",
    "ModelUsage",
    "StreamChunk",
    "CallOptions",
    "ModelCapability",
    "ModelRegistry",
    "ModelClient",
    "OpenAIProvider",
    "AnthropicProvider",
    "model_registry",
    "ModelMonitor",
    "CallStatus",
    "SpanKind",
    "ModelCallSpan",
    "TokenUsage",
    "TokenUsageTracker",
    "CallTrace",
    "CostBudget",
    "model_monitor",
    "MemoryMessage",
    "CompactionStrategy",
    "KeyInfo",
    "CompactionResult",
    "ImportanceScorer",
    "KeyInfoExtractor",
    "SummaryGenerator",
    "MemoryCompactor",
    "MemoryCompactionManager",
    "VectorDocument",
    "SearchResult",
    "EmbeddingModel",
    "OpenAIEmbedding",
    "SimpleEmbedding",
    "VectorStore",
    "InMemoryVectorStore",
    "VectorMemoryStore",
    "MemoryRetriever",
    "vector_memory_store",
    "SandboxType",
    "SandboxStatus",
    "SandboxConfig",
    "SandboxBase",
    "LocalSandbox",
    "DockerSandbox",
    "SandboxManager",
    "ExecutionResult",
    "sandbox_manager",
    "ReasoningStrategy",
    "ReasoningStep",
    "ReasoningResult",
    "StrategyType",
    "ReActStrategy",
    "PlanAndExecuteStrategy",
    "ChainOfThoughtStrategy",
    "ReflectionStrategy",
    "ReasoningStrategyFactory",
    "reasoning_strategy_factory",
    "MetricType",
    "LogLevel",
    "SpanStatus",
    "Metric",
    "Span",
    "LogEntry",
    "MetricsCollector",
    "Tracer",
    "StructuredLogger",
    "ObservabilityManager",
    "observability_manager",
    "ConfigSource",
    "ConfigChange",
    "ConfigVersion",
    "AgentConfig",
    "ConfigSchema",
    "ConfigLoader",
    "ConfigValidator",
    "ConfigManager",
    "GlobalConfig",
    "get_config",
    "set_config",
    "config_manager",
    "ExecutionState",
    "CheckpointType",
    "ContextLayer",
    "ExecutionContext",
    "Checkpoint",
    "ExecutionSnapshot",
    "StateStore",
    "FileStateStore",
    "MemoryStateStore",
    "CheckpointManager",
    "CircuitBreaker",
    "TaskQueue",
    "StateCompressor",
    "AgentHarness",
    "agent_harness",
    "ValidationLevel",
    "ValidationCategory",
    "ValidationResult",
    "ContextValidator",
    "LayeredContextValidator",
    "ContextValidationManager",
    "context_validator",
    "layered_context_validator",
    "context_validation_manager",
    "ReplayEventType",
    "ReplayMode",
    "ReplayEvent",
    "ExecutionRecording",
    "ExecutionReplayer",
    "ExecutionAnalyzer",
    "ReplayManager",
    "replay_manager",
    "LongTaskStatus",
    "ProgressPhase",
    "ProgressReport",
    "LongTaskConfig",
    "LongRunningTaskExecutor",
    "long_running_task_executor",
    "ToolMetadata",
    "ToolResult",
    "ToolBase",
    "ToolRegistry",
    "tool",
    "register_builtin_tools",
    "BashTool",
    "ReadTool",
    "WriteTool",
    "ListFilesTool",
    "AskUserTool",
    "QuestionTool",  # 向后兼容别名
    "register_interaction_tools",
    "WebFetchTool",
    "WebSearchTool",
    "APICallTool",
    "GraphQLTool",
    "register_network_tools",
    "MCPToolAdapter",
    "MCPToolRegistry",
    "MCPConnectionManager",
    "adapt_mcp_tool",
    "register_mcp_tools",
    "mcp_connection_manager",
    "ActionToolAdapter",
    "ActionToolRegistry",
    "action_to_tool",
    "register_actions_from_module",
    "create_action_tools_from_resources",
    "ActionTypeMapper",
    "default_action_mapper",
    "register_analysis_tools",
    "register_all_tools",
    "create_default_tool_registry",
    "ProgressEventType",
    "ProgressEvent",
    "ProgressBroadcaster",
    "progress_broadcaster",
    "LLMProvider",
    "MessageRole",
    "LLMMessage",
    "LLMUsage",
    "LLMResponse",
    "LLMConfig",
    "LLMAdapter",
    "OpenAIAdapter",
    "AnthropicAdapter",
    "LLMFactory",
    "llm_factory",
    "ProductionAgent",
    "AgentBuilder",
    "ProductionAgentInteractionMixin",
    "ProductionAgentWithInteraction",
    "TaskScene",
    "TruncationStrategy",
    "DedupStrategy",
    "ValidationLevel",
    "OutputFormat",
    "ResponseStyle",
    "TruncationPolicy",
    "CompactionPolicy",
    "DedupPolicy",
    "TokenBudget",
    "ContextPolicy",
    "PromptPolicy",
    "ToolPolicy",
    "SceneProfile",
    "SceneProfileBuilder",
    "create_scene",
    "ProcessResult",
    "ProtectedBlock",
    "ContextProcessor",
    "ContextProcessorFactory",
    "SceneRegistry",
    "get_scene_profile",
    "list_available_scenes",
    "create_custom_scene",
    "ModeSwitchResult",
    "ModeHistory",
    "ModeManager",
    "ModeManagerFactory",
    "get_mode_manager",
    "SceneConfigError",
    "SceneConfigLoader",
    "scene_config_loader",
    "load_scene_config",
    "load_scenes_from_directory",
    "AgentPhase",
    "HookPriority",
    "HookResult",
    "HookContext",
    "SceneHook",
    "PromptTemplate",
    "SystemPromptTemplate",
    "ContextProcessorExtension",
    "ToolSelectorExtension",
    "OutputRendererExtension",
    "SceneStrategy",
    "SceneStrategyRegistry",
    "SceneStrategyExecutor",
    "scene_hook",
    "create_simple_hook",
    "GENERAL_SYSTEM_PROMPT",
    "CODING_SYSTEM_PROMPT",
    "GENERAL_STRATEGY",
    "CODING_STRATEGY",
    "CodeBlockProtectionHook",
    "FilePathPreservationHook",
    "CodeStyleInjectionHook",
    "ProjectContextInjectionHook",
    "ToolOutputFormatterHook",
    "ErrorRecoveryHook",
    "register_builtin_strategies",
    "SoftwareEngineeringConfigLoader",
    "SoftwareEngineeringConfig",
    "CodeQualityChecker",
    "DesignPrinciple",
    "AntiPattern",
    "QualityGate",
    "SecurityConstraint",
    "get_software_engineering_config",
    "check_code_quality",
    "SoftwareEngineeringIntegrator",
    "CodingStrategyEnhancer",
    "EngineeringCheckResult",
    "CheckPoint",
    "create_coding_strategy_enhancer",
    "integrate_with_agent",
    "SoftwareEngineeringLoaderV2",
    "LightweightCodeChecker",
    "LightConfig",
    "FullConfig",
    "InjectionLevel",
    "DevScene",
    "get_se_loader",
    "get_light_se_prompt",
    "get_standard_se_prompt",
    "quick_code_check",
    "SoftwareEngineeringHook",
    "SoftwareEngineeringCheckHook",
    "create_se_hooks",
    # Enhanced Interaction System
    "EnhancedInteractionManager",
    "AuthorizationCache",
    "create_enhanced_interaction_manager",
    # Multi-Agent Collaboration System
    "SharedContext",
    "SharedMemory",
    "Artifact",
    "ResourceScope",
    "ResourceBinding",
    "MultiAgentOrchestrator",
    "ExecutionStrategy",
    "TaskPlan",
    "SubTask",
    "TaskStatus",
    "TaskResult",
    "MultiAgentExecutionResult",
    "AgentTeam",
    "AgentRole",
    "AgentStatus",
    "WorkerAgent",
    "TeamConfig",
    "TaskPlanner",
    "DecompositionStrategy",
    "TaskDependency",
    "TaskPriority",
    "AgentRouter",
    "RoutingStrategy",
    "AgentCapability",
    "AgentSelectionResult",
    "TeamMessenger",
    "MessageType",
    "AgentMessage",
    "BroadcastMessage",
    "TeamMonitor",
    "TeamMetrics",
    "AgentMetrics",
    "ExecutionProgress",
    # Product-Agent Binding System
    "MultiAgentConfig",
    "AgentTeamConfig",
    "AppAgentMapping",
    "ProductAgentRegistry",
    "product_agent_registry",
    "AgentResource",
    "AppResource",
    "BindingResult",
    "ResourceResolver",
    "ProductAgentBinding",
    "get_product_agent_binding",
    # Subagent Delegation System
    "SubagentStatus",
    "TaskPermission",
    "SubagentSession",
    "SubagentResult",
    "TaskPermissionRule",
    "TaskPermissionConfig",
    "SubagentInfo",
    "SubagentRegistry",
    "SubagentManager",
    "subagent_manager",
    "ClaudeCodeCompatibleMemory",
    "GptsMemoryAdapter",
    "MessageConverter",
    "gpts_to_agent",
    "agent_to_gpts",
    # Improved Session Compaction
    "CompactionTrigger",
    "ContentProtector",
    "ProtectedContent",
    "KeyInfoExtractor",
    "KeyInfo",
    "ImprovedSessionCompaction",
    "ImprovedCompactionConfig",
    "ImprovedSessionCompactionAlias",
    # Enhanced Agent Module
    "DecisionType",
    "Decision",
    "ActionResult",
    "EnhancedAgentInfo",
    "EnhancedPermissionChecker",
    "EnhancedToolRegistry",
    "EnhancedSubagentSession",
    "EnhancedSubagentResult",
    "EnhancedSubagentManager",
    "EnhancedTaskStatus",
    "EnhancedTask",
    "TaskList",
    "TeamManager",
    "AutoCompactionManager",
    "EnhancedAgentBase",
    "EnhancedProductionAgent",
    # Agent Decorators
    "agent",
    "decide",
    "act",
    "tool",
    "AgentRegistry",
    "register_all_decorated",
    "AgentDefinition",
    # MCP Integration
    "MCPToolConfig",
    "MCPServerConfig",
    "MCPToolAdapter",
    "MCPToolRegistry",
    "MCPEnabledAgent",
    "create_mcp_agent",
    # Project Memory System (CLAUDE.md style)
    "MemoryPriority",
    "MemorySource",
    "MemoryLayer",
    "ProjectMemoryConfig",
    "ImportDirective",
    "MemoryConsolidationConfig",
    "ProjectMemoryInterface",
    "ProjectMemoryManager",
    # Context Isolation System
    "ContextIsolationMode",
    "ContextWindow",
    "MemoryScope",
    "ResourceBinding",
    "ToolAccessRule",
    "SubagentContextConfig",
    "IsolatedContext",
    "ContextIsolationInterface",
    "ContextIsolationManager",
    # Filesystem Integration
    "ClaudeMdFrontMatter",
    "ClaudeMdSection",
    "ClaudeMdDocument",
    "ClaudeMdParser",
    "ClaudeCompatibleAdapter",
    "ClaudeMdWatcher",
    "SceneHookPriority",
    "SceneAgentPhase",
    "SceneHookContext",
    "SceneHookResult",
    "SceneHook",
    "AutoMemoryHook",
    "ImportantDecisionHook",
    "ErrorRecoveryHook",
    "KnowledgeExtractionHook",
    "HookRegistry",
    "create_default_hooks",
    "MemoryArtifact",
    "AgentFileSystemMemoryExtension",
    "MemoryFileSync",
    "PromptFileManager",
    "register_project_memory_hooks",
    # VIS Push Manager
    "VISPushManager",
    "VISPushConfig",
    "create_vis_push_manager",
    # VIS Push Hooks
    "VISPushHook",
    "VISPushThinkHook",
    "VISPushToolHook",
    "create_vis_push_hooks",
]

# Enhanced Interaction System
from .enhanced_interaction import (
    EnhancedInteractionManager,
    AuthorizationCache,
    create_enhanced_interaction_manager,
)

# Multi-Agent Collaboration System
from .multi_agent import (
    SharedContext,
    SharedMemory,
    Artifact,
    ResourceScope,
    ResourceBinding,
    MultiAgentOrchestrator,
    ExecutionStrategy,
    TaskPlan,
    SubTask,
    TaskStatus,
    TaskResult,
    ExecutionResult as MultiAgentExecutionResult,
    AgentTeam,
    AgentRole,
    AgentStatus,
    WorkerAgent,
    TeamConfig,
    TaskPlanner,
    DecompositionStrategy,
    TaskDependency,
    TaskPriority,
    AgentRouter,
    RoutingStrategy,
    AgentCapability,
    AgentSelectionResult,
    TeamMessenger,
    MessageType,
    AgentMessage,
    BroadcastMessage,
    TeamMonitor,
    TeamMetrics,
    AgentMetrics,
    ExecutionProgress,
)

# Product-Agent Binding System
from .product_agent_registry import (
    AgentConfig as MultiAgentConfig,
    AgentTeamConfig,
    AppAgentMapping,
    ProductAgentRegistry,
    product_agent_registry,
)
from .agent_binding import (
    AgentResource,
    AppResource,
    BindingResult,
    ResourceResolver,
    ProductAgentBinding,
    get_product_agent_binding,
)

from .subagent_manager import (
    SubagentStatus,
    TaskPermission,
    SubagentSession,
    SubagentResult,
    TaskPermissionRule,
    TaskPermissionConfig,
    SubagentInfo,
    SubagentRegistry,
    SubagentManager,
    subagent_manager,
)

# Async Task Manager
from .async_task_manager import (
    AsyncTaskStatus,
    AsyncTaskSpec,
    AsyncTaskState,
    AsyncTaskManager,
)

# Unified Memory Framework
from .unified_memory import (
    MemoryItem,
    MemoryType,
    SearchOptions,
    UnifiedMemoryInterface,
    MemoryConsolidationResult,
    FileBackedStorage,
    UnifiedMemoryManager,
    ClaudeCodeCompatibleMemory,
    GptsMemoryAdapter,
    MessageConverter,
    gpts_to_agent,
    agent_to_gpts,
)

# Project Memory System (CLAUDE.md style)
from .project_memory import (
    MemoryPriority,
    MemorySource,
    MemoryLayer,
    ProjectMemoryConfig,
    ImportDirective,
    MemoryConsolidationConfig,
    ProjectMemoryInterface,
)
from .project_memory.manager import ProjectMemoryManager

# Context Isolation System
from .context_isolation import (
    ContextIsolationMode,
    ContextWindow,
    MemoryScope,
    ResourceBinding,
    ToolAccessRule,
    SubagentContextConfig,
    IsolatedContext,
    ContextIsolationInterface,
)
from .context_isolation.manager import ContextIsolationManager

# Filesystem Integration
from .filesystem import (
    # CLAUDE.md compatibility
    ClaudeMdFrontMatter,
    ClaudeMdSection,
    ClaudeMdDocument,
    ClaudeMdParser,
    ClaudeCompatibleAdapter,
    ClaudeMdWatcher,
    # Auto memory hooks
    HookPriority as SceneHookPriority,
    AgentPhase as SceneAgentPhase,
    HookContext as SceneHookContext,
    HookResult as SceneHookResult,
    SceneHook,
    AutoMemoryHook,
    ImportantDecisionHook,
    ErrorRecoveryHook,
    KnowledgeExtractionHook,
    HookRegistry,
    create_default_hooks,
    # Integration
    MemoryArtifact,
    AgentFileSystemMemoryExtension,
    MemoryFileSync,
    PromptFileManager,
    register_project_memory_hooks,
)

# Improved Session Compaction
from .improved_compaction import (
    CompactionTrigger,
    ContentProtector,
    ProtectedContent,
    KeyInfoExtractor,
    KeyInfo,
    ImprovedSessionCompaction,
    CompactionConfig as ImprovedCompactionConfig,
    SessionCompaction as ImprovedSessionCompactionAlias,
)

# Enhanced Agent Module
from .enhanced_agent import (
    DecisionType,
    Decision,
    ActionResult,
    AgentInfo as EnhancedAgentInfo,
    PermissionChecker as EnhancedPermissionChecker,
    ToolRegistry as EnhancedToolRegistry,
    SubagentSession as EnhancedSubagentSession,
    SubagentResult as EnhancedSubagentResult,
    SubagentManager as EnhancedSubagentManager,
    TaskStatus as EnhancedTaskStatus,
    Task as EnhancedTask,
    TaskList,
    TeamManager,
    AutoCompactionManager,
    AgentBase as EnhancedAgentBase,
    ProductionAgent as EnhancedProductionAgent,
)
