[agent.llm]
temperature = 0.5

[[agent.llm.providers]]
provider = "proxy/openai"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "sk-b882358e22b04b279860a45a9c89764f"

[[agent.llm.providers.model]]
name = "qwen-plus"
temperature = 0.7
max_new_tokens = 4096

[[agent.llm.providers.model]]
name = "deepseek-r1"
temperature = 0.7
max_new_tokens = 4096